apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickhire
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/QuickHire.git
    targetRevision: main
    path: k8s
    directory:
      recurse: true
      exclude: '{argocd-application.yaml,observability/**}'
  destination:
    server: https://kubernetes.default.svc
    namespace: quickhire
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true