apiVersion: v1
kind: Secret
metadata:
  name: quickhire-secret
  namespace: quickhire
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: change-me
  JWT_ACCESS_SECRET: change-me-access-secret-min-32-chars
  JWT_REFRESH_SECRET: change-me-refresh-secret-min-32-chars