apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: quickhire
spec:
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: quickhire-backend
  namespace: quickhire
spec:
  selector:
    app: quickhire-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30081
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: quickhire-frontend
  namespace: quickhire
spec:
  selector:
    app: quickhire-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort